export const DEFAULT_JOB_POOL_SEGMENTS = [
  ["frontend", "Frontend Developer"],
  ["backend", "Backend Developer"],
  ["full-stack", "Full Stack Developer"],
  ["react", "React Developer"],
  ["nextjs", "Next.js Developer"],
  ["nodejs", "Node.js Developer"],
  ["python", "Python Developer"],
  ["java", "Java Developer"],
  ["dotnet", ".NET Developer"],
  ["mobile", "Mobile Developer"],
  ["devops", "DevOps Engineer"],
  ["data", "Data Analyst"],
  ["data-science", "Data Scientist"],
  ["product", "Product Manager"],
  ["project", "Project Manager"],
  ["ui-ux", "UI UX Designer"],
  ["qa", "QA Engineer"],
  ["cybersecurity", "Cybersecurity Engineer"],
  ["digital-marketing", "Digital Marketing Specialist"],
  ["sales", "Sales Representative"],
] as const;
