"use client";

import { useState } from "react";
import { ArrowLeft, BriefcaseBusiness, CheckCircle2, ChevronLeft, CircleUserRound, Clock3, FileCheck2, MessageSquareText, Sparkles, X } from "lucide-react";
import { SectionTitle } from "../_components/ui";
import { useToast } from "../_components/panel-shell";

export default function InterviewPage() {
  const notify = useToast();
  const [started, setStarted] = useState(false);
  const [mode, setMode] = useState("مصاحبه Product Lead فلایتیو");
  const [answer, setAnswer] = useState("");
  const [feedback, setFeedback] = useState(false);
  const startPractice = (selectedMode: string) => { setMode(selectedMode); setStarted(true); setFeedback(false); setAnswer(""); };
  return <><SectionTitle title="آمادگی مصاحبه" description="با سؤال‌های شخصی‌سازی‌شده برای رزومه و موقعیت موردنظرت تمرین کن." /><div className="interview-hero"><div><span className="soft-badge"><Sparkles size={14} /> تمرین پیشنهادی</span><h2>مصاحبه Product Lead فلایتیو</h2><p>۱۲ سؤال تخصصی و رفتاری براساس شرح شغل و رزومه‌ای که ارسال کرده‌ای.</p><div className="interview-meta"><span><Clock3 size={15} /> حدود ۲۵ دقیقه</span><span><MessageSquareText size={15} /> بازخورد هوشمند</span></div><button className="light-btn" onClick={() => startPractice("مصاحبه Product Lead فلایتیو")}>{started ? "ادامه تمرین" : "شروع مصاحبه آزمایشی"} <ArrowLeft size={17} /></button></div><div className="orb"><MessageSquareText size={40} /></div></div>{started && <section className="panel interview-session"><div className="session-head"><div><span className="great-label">جلسه فعال</span><h3>{mode}</h3></div><button className="icon-button" onClick={() => setStarted(false)}><X size={19} /></button></div><div className="question-box"><span>سؤال ۱ از ۵</span><h2>از موقعیتی بگو که بین نیاز کاربر و هدف کسب‌وکار تعارض وجود داشت؛ چطور تصمیم گرفتی؟</h2></div><label>پاسخ تو<textarea value={answer} onChange={(event) => { setAnswer(event.target.value); setFeedback(false); }} placeholder="پاسخت را با ساختار موقعیت، وظیفه، اقدام و نتیجه بنویس..." /></label>{feedback && <div className="feedback-box"><CheckCircle2 size={19} /><div><strong>شروع خوبی بود</strong><p>تصمیمت روشن است؛ برای قوی‌ترشدن پاسخ، نتیجه را با یک عدد یا شاخص محصول کامل کن.</p></div></div>}<div className="session-actions"><button className="secondary-btn" onClick={() => { setAnswer(""); setFeedback(false); notify("سؤال بعدی نمایش داده شد"); }}>سؤال بعدی <ArrowLeft size={16} /></button><button className="primary-btn" disabled={!answer.trim()} onClick={() => setFeedback(true)}><Sparkles size={17} /> دریافت بازخورد</button></div></section>}<div className="practice-grid">{[{ icon: CircleUserRound, tone: "lavender", title: "سؤال‌های رفتاری", text: "تمرین پاسخ با چارچوب STAR و دریافت پیشنهاد برای بهترشدن روایت." }, { icon: BriefcaseBusiness, tone: "mint", title: "سؤال‌های تخصصی محصول", text: "مسئله‌های واقعی درباره استراتژی، متریک، اولویت‌بندی و کشف محصول." }, { icon: FileCheck2, tone: "peach", title: "مرور رزومه ارسالی", text: "نقاطی که احتمال دارد مصاحبه‌گر درباره آن‌ها عمیق‌تر سؤال کند." }].map((item) => { const Icon = item.icon; return <article className="panel" key={item.title}><div className={`icon-tile ${item.tone}`}><Icon size={22} /></div><h3>{item.title}</h3><p>{item.text}</p><button className="text-btn" onClick={() => startPractice(item.title)}>شروع تمرین <ChevronLeft size={16} /></button></article>; })}</div></>;
}
