export const skillSuggestions = [
  "Adobe After Effects", "Adobe Illustrator", "Adobe InDesign", "Adobe Photoshop", "Adobe Premiere Pro",
  "Agile Methodologies", "Amazon Web Services (AWS)", "Android Development", "Angular", "Ansible",
  "Apache Kafka", "API Development", "API Integration", "Artificial Intelligence (AI)", "ASP.NET",
  "AutoCAD", "Automation", "Azure DevOps", "B2B Marketing", "B2B Sales", "Bash", "Big Data",
  "Blockchain", "Bootstrap", "Brand Management", "Brand Strategy", "Budget Management", "Business Analysis",
  "Business Development", "Business Intelligence (BI)", "Business Strategy", "C", "C#", "C++", "Canva",
  "Change Management", "CI/CD", "Cloud Computing", "Cloud Security", "Coaching", "Communication",
  "Computer Vision", "Conflict Resolution", "Content Marketing", "Content Strategy", "Copywriting",
  "Corporate Communications", "Critical Thinking", "CRM", "CSS", "Customer Experience", "Customer Relationship Management",
  "Customer Service", "Cybersecurity", "Dart", "Data Analysis", "Data Analytics", "Data Engineering",
  "Data Modeling", "Data Science", "Data Visualization", "Database Administration", "Deep Learning", "Design Patterns",
  "Design Thinking", "DevOps", "Digital Marketing", "Digital Strategy", "Django", "Docker", "Elasticsearch",
  "Email Marketing", "Employee Engagement", "Enterprise Architecture", "Entity Framework", "Entrepreneurship",
  "Express.js", "FastAPI", "Figma", "Financial Analysis", "Financial Modeling", "Firebase", "Flask", "Flutter",
  "Front-End Development", "Full-Stack Development", "Git", "GitHub", "GitLab", "Go", "Google Ads",
  "Google Analytics", "Google Cloud Platform (GCP)", "Graphic Design", "GraphQL", "Growth Marketing", "HTML",
  "Human Resources (HR)", "Illustration", "Information Architecture", "Information Security", "iOS Development",
  "Java", "JavaScript", "Jenkins", "Jira", "jQuery", "JSON", "Kotlin", "Kubernetes", "Laravel", "Leadership",
  "Linux", "Machine Learning", "Market Analysis", "Market Research", "Marketing Strategy", "Mentoring",
  "Microsoft Azure", "Microsoft Excel", "Microsoft Office", "Microsoft Power BI", "Microsoft PowerPoint",
  "Microsoft SQL Server", "Microservices", "MongoDB", "MySQL", "Negotiation", "NestJS", "Network Security",
  "Next.js", "Node.js", "NoSQL", "NumPy", "Object-Oriented Programming (OOP)", "Operations Management",
  "Oracle Database", "Pandas", "Performance Marketing", "PHP", "PostgreSQL", "Problem Solving", "Product Design",
  "Product Development", "Product Management", "Product Marketing", "Project Management", "Prompt Engineering",
  "Prototyping", "Public Relations", "Python", "PyTorch", "Quality Assurance", "R", "React.js", "React Native",
  "Redis", "Redux.js", "REST APIs", "Risk Management", "Ruby on Rails", "Rust", "Sales", "Sales Management",
  "Salesforce", "Sass", "Scrum", "Search Engine Marketing (SEM)", "Search Engine Optimization (SEO)",
  "Security", "Shell Scripting", "Social Media Marketing", "Software Architecture", "Software Development",
  "Software Development Life Cycle (SDLC)", "Software Testing", "Spring Boot", "SQL", "Stakeholder Management",
  "Strategic Planning", "Swift", "System Design", "Tableau", "Tailwind CSS", "Team Building", "Team Leadership",
  "TensorFlow", "Terraform", "Time Management", "Training", "Troubleshooting", "TypeScript", "UI Design",
  "Unit Testing", "Unity", "Unreal Engine", "User Experience (UX)", "User Interface Design", "User Research",
  "Vue.js", "Web Design", "Web Development", "Web Services", "WordPress", "Writing",
  "ارتباط مؤثر", "استراتژی کسب‌وکار", "برنامه‌ریزی استراتژیک", "تحلیل داده", "تفکر انتقادی",
  "توسعه کسب‌وکار", "حل مسئله", "رهبری تیم", "طراحی تجربه کاربری", "طراحی رابط کاربری",
  "فروش", "مدیریت پروژه", "مدیریت محصول", "مذاکره", "هوش مصنوعی",
] as const;
